services:
  db:
    command: postgres -c work_mem=8000
    environment:
      - POSTGRES_USER=satori
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=admin_db
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD-SHELL
        - pg_isready
      timeout: 5s
    image: pgvector/pgvector:pg16
    shm_size: 1gb
    ports:
      - "127.0.0.1:5434:5432"